/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.warehouse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author INDUL
 */
public final class add_n_s_j1 extends javax.swing.JFrame {

    /**
     * Creates new form add_n_s_j1
     */
    public add_n_s_j1() {
        initComponents();
        autoID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroundpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_quantity = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtcater = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtduration1 = new javax.swing.JComboBox<>();
        txtspace1 = new javax.swing.JComboBox<>();
        txtquantity = new javax.swing.JComboBox<>();
        backgroundimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Backgroundpanel.setBackground(new java.awt.Color(0, 102, 153));
        Backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wh small W.png"))); // NOI18N
        Backgroundpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 130));

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add New Storage Job");
        Backgroundpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 470, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Catargory");
        Backgroundpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 100, 20));

        lbl_quantity.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(lbl_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 230, 20));

        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        Backgroundpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 10, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(":");
        Backgroundpanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 10, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        Backgroundpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 10, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        Backgroundpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 10, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        Backgroundpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 10, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Emp Name");
        Backgroundpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 100, 20));

        txtname.setBackground(new java.awt.Color(204, 204, 204));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(null);
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        Backgroundpanel.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 230, 20));

        jButton4.setText("Add Job");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 90, 30));

        txtcater.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Electrical ", "Raw Materials", "Wood" }));
        txtcater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaterActionPerformed(evt);
            }
        });
        Backgroundpanel.add(txtcater, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 230, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Duration (Day)");
        Backgroundpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 130, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Space (ft)");
        Backgroundpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");
        Backgroundpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 100, 30));

        txtduration1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        txtduration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtduration1ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(txtduration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 230, -1));

        txtspace1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "25", "50", "75", "100" }));
        txtspace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspace1ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(txtspace1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 230, -1));

        txtquantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "30", "50", "70", "90", "120", "150" }));
        Backgroundpanel.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 230, -1));

        backgroundimg.setBackground(new java.awt.Color(204, 204, 204));
        backgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg.jpg"))); // NOI18N
        Backgroundpanel.add(backgroundimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(966, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        operator Y1 =new operator();
                Y1.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            try {
                // TODO add your handling code here:
                String id = txtname.getText();
                String catergory = (String) txtcater.getSelectedItem();
                String duration = (String) txtduration1.getSelectedItem();
                String space = (String) txtspace1.getSelectedItem();
                String quantity = (String) txtquantity.getSelectedItem();

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/warehouse","root","");
                PreparedStatement pst = con.prepareStatement("insert into job (id,catergory,duration,space,quantity)values(?,?,?,?,?)");
                pst.setString(1, id);
                pst.setString(2, catergory);
                pst.setString(3, duration);
                pst.setString(4, space);
                pst.setString(5, quantity);

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"Job Added Successfully.");

                autoID();


            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

      public void autoID()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/warehouse","root","");
            Statement s = con.createStatement();
            
            ResultSet rs = s.executeQuery("select Max(id) from job");
            rs.next();
            
            rs.getString("Max(id)");
            
            
            if(rs.getString("Max(id)")==null)
            {
                
                txtname.setText("E-1");
            }
            else
            {
                Long id = Long.parseLong(rs.getString("Max(id)").substring(2,rs.getString("Max(id)").length()));
                id++;
                txtname.setText("E-" + String.format("%d", id));
                
                
                
                
            }
         
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void txtcaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaterActionPerformed

    private void txtduration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtduration1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtduration1ActionPerformed

    private void txtspace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspace1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_n_s_j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_n_s_j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_n_s_j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_n_s_j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new add_n_s_j1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroundpanel;
    private javax.swing.JLabel backgroundimg;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_quantity;
    private javax.swing.JComboBox<String> txtcater;
    private javax.swing.JComboBox<String> txtduration1;
    private javax.swing.JTextField txtname;
    private javax.swing.JComboBox<String> txtquantity;
    private javax.swing.JComboBox<String> txtspace1;
    // End of variables declaration//GEN-END:variables
}
