/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.warehouse;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author INDUL
 */
public class calculate_bill_of_storage_job extends javax.swing.JFrame {

    /**
     * Creates new form calculate_bill_of_storage_job
     */
    public calculate_bill_of_storage_job() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroundpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        catergory = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        space = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        duration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        duration1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        space11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        quantity2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        backgroundimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Backgroundpanel.setBackground(new java.awt.Color(0, 102, 153));
        Backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wh small W.png"))); // NOI18N
        Backgroundpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 150, 130));

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Calculate the Bill of Storage Job");
        Backgroundpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 730, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Catargory");
        Backgroundpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 100, 20));

        catergory.setEditable(false);
        catergory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        catergory.setBorder(null);
        catergory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catergoryActionPerformed(evt);
            }
        });
        Backgroundpanel.add(catergory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 230, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        Backgroundpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 100, 30));

        quantity.setEditable(false);
        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity.setBorder(null);
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        Backgroundpanel.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 230, 20));

        jButton2.setText("Search");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 90, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 230, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 230, 20));

        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Space");
        Backgroundpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 100, 30));

        space.setEditable(false);
        space.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        space.setBorder(null);
        space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceActionPerformed(evt);
            }
        });
        Backgroundpanel.add(space, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 230, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 230, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Duration");
        Backgroundpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 100, 30));

        duration.setEditable(false);
        duration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration.setBorder(null);
        duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationActionPerformed(evt);
            }
        });
        Backgroundpanel.add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 230, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 230, 20));

        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 230, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        Backgroundpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 10, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(":");
        Backgroundpanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 10, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        Backgroundpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 10, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        Backgroundpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 10, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        Backgroundpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 10, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Emp No.");
        Backgroundpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 20));

        no.setBackground(new java.awt.Color(204, 204, 204));
        no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        no.setBorder(null);
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        Backgroundpanel.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 230, 20));

        jButton4.setText("Calculate Bill");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 90, 30));

        jButton5.setText("Done");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 90, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Duration");
        Backgroundpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 70, 30));

        duration1.setEditable(false);
        duration1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration1.setBorder(null);
        duration1.setOpaque(false);
        duration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration1ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(duration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 230, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Space");
        Backgroundpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 50, 30));

        space11.setEditable(false);
        space11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        space11.setBorder(null);
        space11.setOpaque(false);
        space11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space11ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(space11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 230, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total");
        Backgroundpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 70, 30));

        quantity2.setEditable(false);
        quantity2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity2.setBorder(null);
        quantity2.setOpaque(false);
        quantity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity2ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(quantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 230, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Quantity");
        Backgroundpanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 70, 30));

        total.setEditable(false);
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setBorder(null);
        total.setOpaque(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        Backgroundpanel.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 230, 20));

        backgroundimg.setBackground(new java.awt.Color(204, 204, 204));
        backgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg.jpg"))); // NOI18N
        Backgroundpanel.add(backgroundimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(966, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catergoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catergoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catergoryActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
                String str = no.getText();
                //Database Connection
                Class.forName("com.mysql.jdbc.Driver");  
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/warehouse","root","");
                PreparedStatement st = con.prepareStatement("select * from job where id=?");
                st.setString(1, str);
                //Excuting Query
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    String s = rs.getString(1);
                    String s1 = rs.getString(2);
                    String s2 = rs.getString(3);
                    String s3 = rs.getString(4);
                    String s4 = rs.getString(5);
                    //Sets Records in TextFields.
                    no.setText(s);
                    catergory.setText(s1);
                    duration.setText(s2);
                    space.setText(s3);
                    quantity.setText(s4);
                    no.requestFocus();
                } else {
                 
                 catergory.setText("");
                 duration.setText("");
                 space.setText("");
                 quantity.setText("");
                 
                }
                //Create Exception Handler
            } catch (HeadlessException | SQLException ex) {
                System.out.println(ex);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(calculate_bill_of_storage_job.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        manager Y1 =new manager();
                Y1.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceActionPerformed

    private void durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Abstract class
         abstract class Selecte{
         // Abstract method (does not have a body)
         public abstract void selectIte();
       }
       
       // Subclass (inherit from Select)
         class caterg extends Selecte{
            @Override
            public void selectIte(){
               int day;
               int space1;
               int qt;
               day = Integer.parseInt(duration.getText());
               space1 = Integer.parseInt(space.getText());
               qt = Integer.parseInt(quantity.getText());
                        // calculate
                       //duration     
                       if(day<=10){
                       duration1.setText(""+day*10);
                       }
                       else if(day<=20){
                       duration1.setText(""+day*20);
                       }
                       else if(day<=31){
                       duration1.setText(""+day*30);
                       }
                       //space
                       if(space1==5){
                            space11.setText(""+space1*10);
                       }
                       else if(space1==10){
                       space11.setText(""+space1*20);
                       }
                       else if(space1==25){
                       space11.setText(""+space1*30);
                       }
                       else if(space1==50){
                       space11.setText(""+space1*40);
                       }
                       else if(space1==75){
                       space11.setText(""+space1*50);
                       }
                       else if(space1==100){
                       space11.setText(""+space1*60);
                       }
                       //quantity
                       if(qt==10){
                       quantity2.setText(""+qt*10);
                       }
                       else if(qt==30){
                       quantity2.setText(""+qt*30);
                       }
                       else if(qt==50){
                       quantity2.setText(""+qt*50);
                       }
                       else if(qt==70){
                       quantity2.setText(""+qt*70);
                       }
                       else if(qt==90){
                       quantity2.setText(""+qt*90);
                       }
                       else if(qt==120){
                       quantity2.setText(""+qt*120);
                       }
                       else if(qt==150){
                       quantity2.setText(""+qt*150);
                       }
                        
                       
        //total calculate
        //int day1;
        day = Integer.parseInt(duration1.getText());
        //int space11;
        space1 = Integer.parseInt(space11.getText());
        //int qtt;
        qt = Integer.parseInt(quantity2.getText());
        int tot = day+space1+qt;
        
        total.setText(""+tot);
            }
       }
         Selecte s1 = new caterg();
         s1.selectIte();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
                // TODO add your handling code here:
                String id = no.getText();
                String catergor = catergory.getText();
                String duratio = duration1.getText();
                String spac = space11.getText();
                String quantit = quantity2.getText();
                String tota = total.getText();
                
                //Database Connection
                Class.forName("com.mysql.jdbc.Driver");  
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/warehouse","root","");
                PreparedStatement pst = con.prepareStatement("insert into bill (id,catergory,duration,space,quantity,total)values(?,?,?,?,?,?)");
                pst.setString(1, id);
                pst.setString(2, catergor);
                pst.setString(3, duratio);
                pst.setString(4, spac);
                pst.setString(5, quantit);
                pst.setString(6, tota);

                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(calculate_bill_of_storage_job.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void duration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duration1ActionPerformed

    private void space11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_space11ActionPerformed

    private void quantity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity2ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculate_bill_of_storage_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculate_bill_of_storage_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculate_bill_of_storage_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculate_bill_of_storage_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculate_bill_of_storage_job().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroundpanel;
    private javax.swing.JLabel backgroundimg;
    private javax.swing.JTextField catergory;
    private javax.swing.JTextField duration;
    private javax.swing.JTextField duration1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField no;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField quantity2;
    private javax.swing.JTextField space;
    private javax.swing.JTextField space11;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
