/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.warehouse;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author INDUL
 */
public class close_e_s_j1 extends javax.swing.JFrame {

    /**
     * Creates new form reg_user
     */
    public close_e_s_j1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroundpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        catergory = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        space = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        duration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        backgroundimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Backgroundpanel.setBackground(new java.awt.Color(0, 102, 153));
        Backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wh small W.png"))); // NOI18N
        Backgroundpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 130));

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Close Existing Storage Job");
        Backgroundpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 590, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Catargory");
        Backgroundpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 100, 20));

        catergory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        catergory.setBorder(null);
        catergory.setEnabled(false);
        catergory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catergoryActionPerformed(evt);
            }
        });
        Backgroundpanel.add(catergory, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 230, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        Backgroundpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 100, 30));

        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity.setBorder(null);
        quantity.setEnabled(false);
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        Backgroundpanel.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 230, 20));

        jButton2.setText("Search");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 230, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 230, 20));

        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Space");
        Backgroundpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 100, 30));

        space.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        space.setBorder(null);
        space.setEnabled(false);
        space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceActionPerformed(evt);
            }
        });
        Backgroundpanel.add(space, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 230, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 230, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Duration");
        Backgroundpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 100, 30));

        duration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration.setBorder(null);
        duration.setEnabled(false);
        duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationActionPerformed(evt);
            }
        });
        Backgroundpanel.add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 230, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 230, 20));

        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 230, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        Backgroundpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 10, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(":");
        Backgroundpanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 10, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        Backgroundpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 10, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        Backgroundpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 10, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        Backgroundpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 10, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Emp No.");
        Backgroundpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, 20));

        no.setBackground(new java.awt.Color(204, 204, 204));
        no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        no.setBorder(null);
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        Backgroundpanel.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 230, 20));

        jButton4.setText("Delete");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 90, 30));

        backgroundimg.setBackground(new java.awt.Color(204, 204, 204));
        backgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg.jpg"))); // NOI18N
        Backgroundpanel.add(backgroundimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(966, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catergoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catergoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catergoryActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(no.getText().trim().isEmpty() ){
             lbl_name.setText("Number Required.");
        }else{
        try {  
            String str = no.getText();  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/warehouse","root","");  
            PreparedStatement st = con.prepareStatement("select * from job where id=?");  
            st.setString(1, str);  
            //Excuting Query  
            ResultSet rs = st.executeQuery();  
            if (rs.next()) {  
                String s = rs.getString(1);  
                String s1 = rs.getString(2);  
                String s2 = rs.getString(3);  
                String s3 = rs.getString(4);
                String s4 = rs.getString(5);  
                //Sets Records in TextFields.  
                no.setText(s);
                catergory.setText(s1);  
                duration.setText(s2);  
                space.setText(s3);  
                quantity.setText(s4);
                no.requestFocus();
            } else {  
                JOptionPane.showMessageDialog(null, " Number Not Found. \r\n Please Register First.");  
            }  
            //Create Exception Handler  
        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {  
            System.out.println(ex);  
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        operator Y1 =new operator();
                Y1.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceActionPerformed

    private void durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(no.getText().trim().isEmpty() ){
             lbl_name.setText("Number Required.");
        }else{
             int opt =JOptionPane.showConfirmDialog(null, "Are You Sure Delete Job ?","Delete",JOptionPane.YES_NO_OPTION);
            if(opt== 0){
               try {  
                
            String str = no.getText();  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/warehouse","root","");  
            PreparedStatement st = con.prepareStatement("DELETE FROM `job` WHERE id=?");  
            st.setString(1, str); 
            JOptionPane.showMessageDialog(this,"Job Deleted Successfully.");
            //Excuting Query  
                int rs = st.executeUpdate();
               
                no.setText("");
                catergory.setText("");
                duration.setText("");
                space.setText("");
                quantity.setText("");
                no.requestFocus();
            //Create Exception Handler  
        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {  
            System.out.println(ex);  
        } } }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(close_e_s_j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(close_e_s_j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(close_e_s_j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(close_e_s_j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new close_e_s_j1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroundpanel;
    private javax.swing.JLabel backgroundimg;
    private javax.swing.JTextField catergory;
    private javax.swing.JTextField duration;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField no;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField space;
    // End of variables declaration//GEN-END:variables
}
