/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.warehouse;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author INDUL
 */
public class main_page extends javax.swing.JFrame {

    /**
     * Creates new form main_page
     */
    public main_page() {
        initComponents();
        
        showDate();
        showTime();
    }
    
    
    public void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        String dat = s.format (d);
        date.setText(dat);
    }
    
    public void showTime(){
        new Timer (0,new ActionListener(){
            private ActionListener start;
         @Override   

            
            public void actionPerformed(ActionEvent ae) {
              Date d =  new Date();
              SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
              String tim = s.format(d);
              time.setText(tim);
              
            }
        }).start();
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroundpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        backgroundimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 540));
        setResizable(false);

        Backgroundpanel.setBackground(new java.awt.Color(0, 102, 153));
        Backgroundpanel.setPreferredSize(new java.awt.Dimension(950, 540));
        Backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wh small W.png"))); // NOI18N
        Backgroundpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 170));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to");
        Backgroundpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, 100));

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Smart Warehouse");
        Backgroundpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 480, 100));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-manager-48.png"))); // NOI18N
        jButton1.setText("Manager");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 120, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-operator-48.png"))); // NOI18N
        jButton2.setText("Operator");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 120, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cal25.png"))); // NOI18N
        Backgroundpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 30, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-time-64.png"))); // NOI18N
        Backgroundpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 30, 40));

        date.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("date");
        Backgroundpanel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 130, 20));

        time.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("time");
        Backgroundpanel.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 140, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close 30.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 20, 20));

        backgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg.jpg"))); // NOI18N
        Backgroundpanel.add(backgroundimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 970, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(966, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        m_login Y1 =new m_login();
                Y1.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        op_login Y1 =new op_login();
                Y1.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame, "Confirm If you Want to Exit?","EXIT",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
    {
        System.exit(0);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main_page().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroundpanel;
    private javax.swing.JLabel backgroundimg;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
