/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.warehouse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author INDUL
 */
public final class reg_user extends javax.swing.JFrame {

    /**
     * Creates new form reg_user
     */
    public reg_user() {
        initComponents();
        autoID();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroundpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        lbl_nic = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        lbl_mail = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        lbl_add = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        backgroundimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Backgroundpanel.setBackground(new java.awt.Color(0, 102, 153));
        Backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wh small W.png"))); // NOI18N
        Backgroundpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 150, 130));

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Register User");
        Backgroundpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 320, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name");
        Backgroundpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, 20));

        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(null);
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });
        Backgroundpanel.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 230, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone No");
        Backgroundpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 100, 30));

        txtphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphone.setBorder(null);
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtphoneKeyReleased(evt);
            }
        });
        Backgroundpanel.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 230, 20));

        jButton2.setText("Register");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 90, 30));

        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 230, 20));

        lbl_phone.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 230, 20));

        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Backgroundpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nic");
        Backgroundpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 30));

        txtnic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnic.setBorder(null);
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnicKeyReleased(evt);
            }
        });
        Backgroundpanel.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 230, 20));

        lbl_nic.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(lbl_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 230, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-Mail");
        Backgroundpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 100, 30));

        txtmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmail.setBorder(null);
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });
        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmailKeyReleased(evt);
            }
        });
        Backgroundpanel.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 230, 20));

        lbl_mail.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(lbl_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 230, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Address");
        Backgroundpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 100, 30));

        txtadd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtadd.setBorder(null);
        txtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddActionPerformed(evt);
            }
        });
        txtadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaddKeyReleased(evt);
            }
        });
        Backgroundpanel.add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 230, 20));

        lbl_add.setForeground(new java.awt.Color(255, 255, 255));
        Backgroundpanel.add(lbl_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 230, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(":");
        Backgroundpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 10, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        Backgroundpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 10, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(":");
        Backgroundpanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 10, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        Backgroundpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 10, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        Backgroundpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 10, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        Backgroundpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 10, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Emp No");
        Backgroundpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, 20));

        txtno.setBackground(new java.awt.Color(204, 204, 204));
        txtno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtno.setBorder(null);
        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        Backgroundpanel.add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 230, 20));

        backgroundimg.setBackground(new java.awt.Color(204, 204, 204));
        backgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg.jpg"))); // NOI18N
        Backgroundpanel.add(backgroundimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(966, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(txtname.getText().trim().isEmpty() && txtmail.getText().trim().isEmpty() && txtnic.getText().trim().isEmpty() && txtphone.getText().trim().isEmpty() && txtadd.getText().trim().isEmpty() ){
        lbl_name.setText("Name Required.");
        lbl_mail.setText("E-Mail Required.");
        lbl_nic.setText("NIC Required.");
        lbl_phone.setText("Phone No. Required.");
        lbl_add.setText("Address Required.");
        }
        else if(txtname.getText().trim().isEmpty()){
             lbl_name.setText("Name Required.");
        }
        else if(txtmail.getText().trim().isEmpty()){
            lbl_mail.setText("E-Mail Required.");
        }
        else if(txtnic.getText().trim().isEmpty()){
            lbl_nic.setText("NIC Required.");
        }
        else if(txtphone.getText().trim().isEmpty()){
           lbl_phone.setText("Phone No. Required.");
        }
        else if(txtadd.getText().trim().isEmpty()){
             lbl_add.setText("Address Required.");
        }
        else{
        try {
            // TODO add your handling code here:

            
            String no = txtno.getText();
            String name = txtname.getText();
            String email = txtmail.getText();
            String nic = txtnic.getText();
            String phone = txtphone.getText();
            String address = txtadd.getText();
            txtname.requestFocus();
            
            
            
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/warehouse","root","");
            PreparedStatement pst = con.prepareStatement("insert into reg (id,name,email,nic,phone,address)values(?,?,?,?,?,?)");
            pst.setString(1, no);
            pst.setString(2, name);
            pst.setString(3, email);
            pst.setString(4, nic);
            pst.setString(5, phone);
            pst.setString(6, address);
            
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this,"User Registered Successfully.");
            
              autoID();
              
              txtname.setText("");
              txtmail.setText("");
              txtnic.setText("");
              txtphone.setText("");
              txtadd.setText("");
              txtname.requestFocus(); 
              
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        manager Y1 =new manager();
                Y1.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void txtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddActionPerformed

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        lbl_name.setText("");
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailKeyReleased
        // TODO add your handling code here:
        lbl_mail.setText("");
    }//GEN-LAST:event_txtmailKeyReleased

    private void txtnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyReleased
        // TODO add your handling code here:
        lbl_nic.setText("");
    }//GEN-LAST:event_txtnicKeyReleased

    private void txtphoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyReleased
        // TODO add your handling code here:
        lbl_phone.setText("");
    }//GEN-LAST:event_txtphoneKeyReleased

    private void txtaddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddKeyReleased
        // TODO add your handling code here:
         lbl_add.setText("");
    }//GEN-LAST:event_txtaddKeyReleased

     public void autoID()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/warehouse","root","");
            Statement s = con.createStatement();
            
            ResultSet rs = s.executeQuery("select Max(id) from job");
            rs.next();
            
            rs.getString("Max(id)");
            
            
            if(rs.getString("Max(id)")==null)
            {
                
                txtno.setText("E-1");
            }
            else
            {
                Long id = Long.parseLong(rs.getString("Max(id)").substring(2,rs.getString("Max(id)").length()));
                id++;
                txtno.setText("E-" + String.format("%d", id));
                
                
                
                
            }
         
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reg_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reg_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reg_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reg_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new reg_user().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroundpanel;
    private javax.swing.JLabel backgroundimg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_add;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables

   
}
